import type { Business } from "@/types";

export const mockBusinesses: Business[] = [
  {
    id: "biz_1",
    role: "business",
    email: "hello@kweloventures.co.za",
    fullName: "Naledi Sithole",
    companyName: "Kwelo Ventures",
    industry: "Technology",
    website: "https://kwelo.co.za",
    description:
      "Cape Town-based fintech building lending infrastructure for the African SME market.",
    registrationNumber: "2021/123456/07",
    verified: true,
    city: "Cape Town",
    onboardingComplete: true,
    createdAt: "2025-08-12T08:30:00Z",
  },
  {
    id: "biz_2",
    role: "business",
    email: "talent@brightline.studio",
    fullName: "Daniel Pretorius",
    companyName: "Brightline Studio",
    industry: "Design",
    website: "https://brightline.studio",
    description: "Brand and product design studio working with high-growth African startups.",
    registrationNumber: "2019/445566/07",
    verified: true,
    city: "Johannesburg",
    onboardingComplete: true,
    createdAt: "2025-06-02T10:00:00Z",
  },
  {
    id: "biz_3",
    role: "business",
    email: "people@ubuntumarket.co.za",
    fullName: "Thandi Mokoena",
    companyName: "Ubuntu Market",
    industry: "Retail & E-commerce",
    description: "Marketplace for South African artisans, scaling DTC across SADC.",
    verified: false,
    city: "Durban",
    onboardingComplete: true,
    createdAt: "2025-09-18T12:00:00Z",
  },
  {
    id: "biz_4",
    role: "business",
    email: "ops@sasolventures.co.za",
    fullName: "Karabo Modise",
    companyName: "Sasol Ventures Lab",
    industry: "Energy",
    description: "Corporate venture studio investing in energy transition startups.",
    verified: true,
    city: "Johannesburg",
    onboardingComplete: true,
    createdAt: "2025-04-22T09:00:00Z",
  },
  {
    id: "biz_5",
    role: "business",
    email: "hello@yebostudios.co.za",
    fullName: "Aisha Patel",
    companyName: "Yebo Studios",
    industry: "Media & Marketing",
    description: "Independent production house creating content for African brands.",
    verified: true,
    city: "Cape Town",
    onboardingComplete: true,
    createdAt: "2025-07-09T14:00:00Z",
  },
  {
    id: "biz_6",
    role: "business",
    email: "founders@finyaedu.co.za",
    fullName: "Lerato Dube",
    companyName: "Finya Edu",
    industry: "Education",
    description: "Affordable matric prep platform reaching learners across Gauteng and KZN.",
    verified: false,
    city: "Pretoria",
    onboardingComplete: true,
    createdAt: "2025-10-11T11:00:00Z",
  },
];
