import type { Opportunity } from "@/types";

const now = Date.now();
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString();
const daysAhead = (d: number) => new Date(now + d * 86400000).toISOString();

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp_1",
    businessId: "biz_1",
    businessName: "Kwelo Ventures",
    title: "Frontend Engineer (Internship)",
    type: "internship",
    description:
      "Join our product team building lending dashboards in React + TypeScript. You'll ship features end-to-end with mentorship from senior engineers.",
    requirements: [
      "Comfortable with React and TypeScript",
      "Some experience with REST or GraphQL APIs",
      "Eager to learn fintech fundamentals",
    ],
    skills: ["React", "TypeScript", "Figma"],
    location: "Cape Town",
    remote: true,
    compensationType: "stipend",
    compensationAmount: 12000,
    durationWeeks: 12,
    postedAt: daysAgo(2),
    deadline: daysAhead(14),
    status: "open",
    applicantCount: 34,
  },
  {
    id: "opp_2",
    businessId: "biz_2",
    businessName: "Brightline Studio",
    title: "Brand Designer — Short Project",
    type: "short-project",
    description:
      "Design a launch identity for an early-stage African logistics startup. Includes logo, brand system, and 6 launch assets.",
    requirements: ["Strong portfolio of brand work", "Figma fluency"],
    skills: ["Graphic Design", "Figma", "UI/UX Design"],
    location: "Johannesburg",
    remote: true,
    compensationType: "fixed",
    compensationAmount: 18000,
    durationWeeks: 3,
    postedAt: daysAgo(1),
    deadline: daysAhead(7),
    status: "open",
    applicantCount: 18,
  },
  {
    id: "opp_3",
    businessId: "biz_3",
    businessName: "Ubuntu Market",
    title: "Customer Support Associate (Part-time)",
    type: "part-time",
    description:
      "Be the first line of help for our artisan partners. Email, WhatsApp, and occasional calls. 20 hrs/week.",
    requirements: ["Excellent written English", "Empathetic communicator"],
    skills: ["Customer Support", "Copywriting"],
    location: "Durban",
    remote: false,
    compensationType: "hourly",
    compensationAmount: 95,
    durationWeeks: 24,
    postedAt: daysAgo(5),
    deadline: daysAhead(10),
    status: "open",
    applicantCount: 52,
  },
  {
    id: "opp_4",
    businessId: "biz_4",
    businessName: "Sasol Ventures Lab",
    title: "Research Analyst — Energy Transition",
    type: "entry-level",
    description:
      "Support our investment team with primary research on African energy startups. Mix of desk research, interviews, and memo writing.",
    requirements: ["Strong analytical writing", "Comfort with spreadsheets and data"],
    skills: ["Research", "Data Analysis", "Excel"],
    location: "Johannesburg",
    remote: false,
    compensationType: "fixed",
    compensationAmount: 22000,
    durationWeeks: 16,
    postedAt: daysAgo(7),
    deadline: daysAhead(20),
    status: "open",
    applicantCount: 41,
  },
  {
    id: "opp_5",
    businessId: "biz_5",
    businessName: "Yebo Studios",
    title: "Video Editor — Freelance",
    type: "freelance",
    description:
      "Edit 4 short-form pieces per month for a leading FMCG brand. Premiere Pro, motion-friendly editor preferred.",
    requirements: ["Portfolio with social-first edits", "Reliable turnaround"],
    skills: ["Video Editing"],
    location: "Cape Town",
    remote: true,
    compensationType: "fixed",
    compensationAmount: 8500,
    durationWeeks: 8,
    postedAt: daysAgo(3),
    deadline: daysAhead(12),
    status: "open",
    applicantCount: 27,
  },
  {
    id: "opp_6",
    businessId: "biz_6",
    businessName: "Finya Edu",
    title: "Matric Maths Tutor (Part-time)",
    type: "part-time",
    description: "Run small-group online tutorials, 8 hrs/week. Curriculum and tooling provided.",
    requirements: ["Maths distinction at matric or higher", "Patient, clear communicator"],
    skills: ["Tutoring"],
    location: "Remote",
    remote: true,
    compensationType: "hourly",
    compensationAmount: 180,
    durationWeeks: 36,
    postedAt: daysAgo(4),
    deadline: daysAhead(9),
    status: "open",
    applicantCount: 73,
  },
  {
    id: "opp_7",
    businessId: "biz_2",
    businessName: "Brightline Studio",
    title: "Junior UX Designer (Internship)",
    type: "internship",
    description: "12-week immersion across discovery, wireframes, and prototyping.",
    requirements: ["A portfolio piece showing your process", "Curiosity over polish"],
    skills: ["UI/UX Design", "Figma"],
    location: "Johannesburg",
    remote: false,
    compensationType: "stipend",
    compensationAmount: 10000,
    durationWeeks: 12,
    postedAt: daysAgo(9),
    deadline: daysAhead(5),
    status: "open",
    applicantCount: 88,
  },
  {
    id: "opp_8",
    businessId: "biz_1",
    businessName: "Kwelo Ventures",
    title: "SQL & Data Analyst (Entry-level)",
    type: "entry-level",
    description:
      "Own dashboards and ad-hoc analyses for our credit team. Metabase + Postgres stack.",
    requirements: ["Solid SQL", "A bias for clean charts"],
    skills: ["SQL", "Data Analysis", "Python"],
    location: "Cape Town",
    remote: true,
    compensationType: "fixed",
    compensationAmount: 26000,
    durationWeeks: 24,
    postedAt: daysAgo(6),
    deadline: daysAhead(18),
    status: "open",
    applicantCount: 19,
  },
];
