import type { Student, Graduate } from "@/types";

export const mockStudents: Student[] = [
  {
    id: "stu_1",
    role: "student",
    email: "amahle@students.uct.ac.za",
    fullName: "Amahle Ndlovu",
    university: "University of Cape Town",
    degree: "BSc Computer Science",
    graduationYear: 2026,
    skills: ["React", "TypeScript", "Node.js", "Figma"],
    portfolio: {
      github: "https://github.com/amahle",
      linkedin: "https://linkedin.com/in/amahle",
    },
    cvFileName: "amahle-ndlovu-cv.pdf",
    city: "Cape Town",
    onboardingComplete: true,
    createdAt: "2025-09-01T10:00:00Z",
  },
  {
    id: "stu_2",
    role: "student",
    email: "sipho@students.wits.ac.za",
    fullName: "Sipho Mahlangu",
    university: "University of the Witwatersrand",
    degree: "BCom Marketing",
    graduationYear: 2025,
    skills: ["Marketing", "Social Media", "Copywriting", "SEO"],
    portfolio: { linkedin: "https://linkedin.com/in/sipho" },
    city: "Johannesburg",
    onboardingComplete: true,
    createdAt: "2025-07-14T09:00:00Z",
  },
  {
    id: "stu_3",
    role: "student",
    email: "tasha@students.sun.ac.za",
    fullName: "Tasha van Wyk",
    university: "Stellenbosch University",
    degree: "BA Visual Communication",
    graduationYear: 2026,
    skills: ["UI/UX Design", "Figma", "Graphic Design", "Photography"],
    portfolio: { website: "https://tasha.design" },
    city: "Stellenbosch",
    onboardingComplete: true,
    createdAt: "2025-08-20T08:30:00Z",
  },
];

export const mockGraduates: Graduate[] = [
  {
    id: "grad_1",
    role: "graduate",
    email: "nomsa@hey.co.za",
    fullName: "Nomsa Khumalo",
    university: "University of Pretoria",
    degree: "BEng Industrial",
    graduationYear: 2024,
    yearsSinceGraduation: 1,
    currentRole: "Junior Data Analyst",
    skills: ["Python", "SQL", "Excel", "Data Analysis"],
    portfolio: { linkedin: "https://linkedin.com/in/nomsa" },
    cvFileName: "nomsa-khumalo-cv.pdf",
    city: "Pretoria",
    onboardingComplete: true,
    createdAt: "2025-05-02T10:00:00Z",
  },
  {
    id: "grad_2",
    role: "graduate",
    email: "kabelo@hey.co.za",
    fullName: "Kabelo Maseko",
    university: "University of Johannesburg",
    degree: "BA Media Studies",
    graduationYear: 2023,
    yearsSinceGraduation: 2,
    currentRole: "Freelance Content Strategist",
    skills: ["Content Strategy", "Copywriting", "Video Editing"],
    portfolio: { linkedin: "https://linkedin.com/in/kabelo", website: "https://kabelo.work" },
    city: "Johannesburg",
    onboardingComplete: true,
    createdAt: "2025-03-19T11:00:00Z",
  },
];
