/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentApplicationsRouteImport } from './routes/student.applications'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as OpportunitiesOpportunityIdRouteImport } from './routes/opportunities.$opportunityId'
import { Route as OnboardingStudentRouteImport } from './routes/onboarding.student'
import { Route as OnboardingGraduateRouteImport } from './routes/onboarding.graduate'
import { Route as OnboardingBusinessRouteImport } from './routes/onboarding.business'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as GraduateDashboardRouteImport } from './routes/graduate.dashboard'
import { Route as GraduateApplicationsRouteImport } from './routes/graduate.applications'
import { Route as BusinessDashboardRouteImport } from './routes/business.dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as BusinessOpportunitiesIndexRouteImport } from './routes/business.opportunities.index'
import { Route as BusinessOpportunitiesNewRouteImport } from './routes/business.opportunities.new'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentApplicationsRoute = StudentApplicationsRouteImport.update({
  id: '/student/applications',
  path: '/student/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfileRoute,
} as any)
const OpportunitiesOpportunityIdRoute =
  OpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingStudentRoute = OnboardingStudentRouteImport.update({
  id: '/onboarding/student',
  path: '/onboarding/student',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingGraduateRoute = OnboardingGraduateRouteImport.update({
  id: '/onboarding/graduate',
  path: '/onboarding/graduate',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBusinessRoute = OnboardingBusinessRouteImport.update({
  id: '/onboarding/business',
  path: '/onboarding/business',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/messages/$conversationId',
  path: '/messages/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduateDashboardRoute = GraduateDashboardRouteImport.update({
  id: '/graduate/dashboard',
  path: '/graduate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduateApplicationsRoute = GraduateApplicationsRouteImport.update({
  id: '/graduate/applications',
  path: '/graduate/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDashboardRoute = BusinessDashboardRouteImport.update({
  id: '/business/dashboard',
  path: '/business/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessOpportunitiesIndexRoute =
  BusinessOpportunitiesIndexRouteImport.update({
    id: '/business/opportunities/',
    path: '/business/opportunities/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessOpportunitiesNewRoute =
  BusinessOpportunitiesNewRouteImport.update({
    id: '/business/opportunities/new',
    path: '/business/opportunities/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/business/dashboard': typeof BusinessDashboardRoute
  '/graduate/applications': typeof GraduateApplicationsRoute
  '/graduate/dashboard': typeof GraduateDashboardRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/onboarding/business': typeof OnboardingBusinessRoute
  '/onboarding/graduate': typeof OnboardingGraduateRoute
  '/onboarding/student': typeof OnboardingStudentRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/messages/': typeof MessagesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/business/opportunities/new': typeof BusinessOpportunitiesNewRoute
  '/business/opportunities/': typeof BusinessOpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/business/dashboard': typeof BusinessDashboardRoute
  '/graduate/applications': typeof GraduateApplicationsRoute
  '/graduate/dashboard': typeof GraduateDashboardRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/onboarding/business': typeof OnboardingBusinessRoute
  '/onboarding/graduate': typeof OnboardingGraduateRoute
  '/onboarding/student': typeof OnboardingStudentRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/messages': typeof MessagesIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/business/opportunities/new': typeof BusinessOpportunitiesNewRoute
  '/business/opportunities': typeof BusinessOpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/business/dashboard': typeof BusinessDashboardRoute
  '/graduate/applications': typeof GraduateApplicationsRoute
  '/graduate/dashboard': typeof GraduateDashboardRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/onboarding/business': typeof OnboardingBusinessRoute
  '/onboarding/graduate': typeof OnboardingGraduateRoute
  '/onboarding/student': typeof OnboardingStudentRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/messages/': typeof MessagesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/business/opportunities/new': typeof BusinessOpportunitiesNewRoute
  '/business/opportunities/': typeof BusinessOpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/reviews'
    | '/settings'
    | '/wallet'
    | '/admin/dashboard'
    | '/business/dashboard'
    | '/graduate/applications'
    | '/graduate/dashboard'
    | '/messages/$conversationId'
    | '/onboarding/business'
    | '/onboarding/graduate'
    | '/onboarding/student'
    | '/opportunities/$opportunityId'
    | '/profile/$userId'
    | '/student/applications'
    | '/student/dashboard'
    | '/messages/'
    | '/opportunities/'
    | '/business/opportunities/new'
    | '/business/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/reviews'
    | '/settings'
    | '/wallet'
    | '/admin/dashboard'
    | '/business/dashboard'
    | '/graduate/applications'
    | '/graduate/dashboard'
    | '/messages/$conversationId'
    | '/onboarding/business'
    | '/onboarding/graduate'
    | '/onboarding/student'
    | '/opportunities/$opportunityId'
    | '/profile/$userId'
    | '/student/applications'
    | '/student/dashboard'
    | '/messages'
    | '/opportunities'
    | '/business/opportunities/new'
    | '/business/opportunities'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/reviews'
    | '/settings'
    | '/wallet'
    | '/admin/dashboard'
    | '/business/dashboard'
    | '/graduate/applications'
    | '/graduate/dashboard'
    | '/messages/$conversationId'
    | '/onboarding/business'
    | '/onboarding/graduate'
    | '/onboarding/student'
    | '/opportunities/$opportunityId'
    | '/profile/$userId'
    | '/student/applications'
    | '/student/dashboard'
    | '/messages/'
    | '/opportunities/'
    | '/business/opportunities/new'
    | '/business/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  WalletRoute: typeof WalletRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  BusinessDashboardRoute: typeof BusinessDashboardRoute
  GraduateApplicationsRoute: typeof GraduateApplicationsRoute
  GraduateDashboardRoute: typeof GraduateDashboardRoute
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  OnboardingBusinessRoute: typeof OnboardingBusinessRoute
  OnboardingGraduateRoute: typeof OnboardingGraduateRoute
  OnboardingStudentRoute: typeof OnboardingStudentRoute
  OpportunitiesOpportunityIdRoute: typeof OpportunitiesOpportunityIdRoute
  StudentApplicationsRoute: typeof StudentApplicationsRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  BusinessOpportunitiesNewRoute: typeof BusinessOpportunitiesNewRoute
  BusinessOpportunitiesIndexRoute: typeof BusinessOpportunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/applications': {
      id: '/student/applications'
      path: '/student/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof StudentApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/opportunities/$opportunityId': {
      id: '/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/opportunities/$opportunityId'
      preLoaderRoute: typeof OpportunitiesOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/student': {
      id: '/onboarding/student'
      path: '/onboarding/student'
      fullPath: '/onboarding/student'
      preLoaderRoute: typeof OnboardingStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/graduate': {
      id: '/onboarding/graduate'
      path: '/onboarding/graduate'
      fullPath: '/onboarding/graduate'
      preLoaderRoute: typeof OnboardingGraduateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/business': {
      id: '/onboarding/business'
      path: '/onboarding/business'
      fullPath: '/onboarding/business'
      preLoaderRoute: typeof OnboardingBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduate/dashboard': {
      id: '/graduate/dashboard'
      path: '/graduate/dashboard'
      fullPath: '/graduate/dashboard'
      preLoaderRoute: typeof GraduateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduate/applications': {
      id: '/graduate/applications'
      path: '/graduate/applications'
      fullPath: '/graduate/applications'
      preLoaderRoute: typeof GraduateApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/dashboard': {
      id: '/business/dashboard'
      path: '/business/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof BusinessDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/opportunities/': {
      id: '/business/opportunities/'
      path: '/business/opportunities'
      fullPath: '/business/opportunities/'
      preLoaderRoute: typeof BusinessOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/opportunities/new': {
      id: '/business/opportunities/new'
      path: '/business/opportunities/new'
      fullPath: '/business/opportunities/new'
      preLoaderRoute: typeof BusinessOpportunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUserIdRoute: ProfileUserIdRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  WalletRoute: WalletRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  BusinessDashboardRoute: BusinessDashboardRoute,
  GraduateApplicationsRoute: GraduateApplicationsRoute,
  GraduateDashboardRoute: GraduateDashboardRoute,
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  OnboardingBusinessRoute: OnboardingBusinessRoute,
  OnboardingGraduateRoute: OnboardingGraduateRoute,
  OnboardingStudentRoute: OnboardingStudentRoute,
  OpportunitiesOpportunityIdRoute: OpportunitiesOpportunityIdRoute,
  StudentApplicationsRoute: StudentApplicationsRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  BusinessOpportunitiesNewRoute: BusinessOpportunitiesNewRoute,
  BusinessOpportunitiesIndexRoute: BusinessOpportunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
