/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedStudentRouteRouteImport } from './routes/_authenticated/student/route'
import { Route as AuthenticatedOnboardingRouteRouteImport } from './routes/_authenticated/onboarding/route'
import { Route as AuthenticatedGraduateRouteRouteImport } from './routes/_authenticated/graduate/route'
import { Route as AuthenticatedBusinessRouteRouteImport } from './routes/_authenticated/business/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedOpportunitiesIndexRouteImport } from './routes/_authenticated/opportunities.index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student/dashboard'
import { Route as AuthenticatedStudentApplicationsRouteImport } from './routes/_authenticated/student/applications'
import { Route as AuthenticatedProfileUserIdRouteImport } from './routes/_authenticated/profile.$userId'
import { Route as AuthenticatedOpportunitiesOpportunityIdRouteImport } from './routes/_authenticated/opportunities.$opportunityId'
import { Route as AuthenticatedOnboardingStudentRouteImport } from './routes/_authenticated/onboarding/student'
import { Route as AuthenticatedOnboardingGraduateRouteImport } from './routes/_authenticated/onboarding/graduate'
import { Route as AuthenticatedOnboardingBusinessRouteImport } from './routes/_authenticated/onboarding/business'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedGraduateDashboardRouteImport } from './routes/_authenticated/graduate/dashboard'
import { Route as AuthenticatedGraduateApplicationsRouteImport } from './routes/_authenticated/graduate/applications'
import { Route as AuthenticatedBusinessDashboardRouteImport } from './routes/_authenticated/business/dashboard'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminPlacementsRouteImport } from './routes/_authenticated/admin/placements'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin/payouts'
import { Route as AuthenticatedAdminDisputesRouteImport } from './routes/_authenticated/admin/disputes'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminBusinessesRouteImport } from './routes/_authenticated/admin/businesses'
import { Route as AuthenticatedBusinessOpportunitiesIndexRouteImport } from './routes/_authenticated/business/opportunities.index'
import { Route as AuthenticatedBusinessOpportunitiesNewRouteImport } from './routes/_authenticated/business/opportunities.new'
import { Route as AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRouteImport } from './routes/_authenticated/business/opportunities.$opportunityId.applicants'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentRouteRoute =
  AuthenticatedStudentRouteRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRouteRoute =
  AuthenticatedOnboardingRouteRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGraduateRouteRoute =
  AuthenticatedGraduateRouteRouteImport.update({
    id: '/graduate',
    path: '/graduate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessRouteRoute =
  AuthenticatedBusinessRouteRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpportunitiesIndexRoute =
  AuthenticatedOpportunitiesIndexRouteImport.update({
    id: '/opportunities/',
    path: '/opportunities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentApplicationsRoute =
  AuthenticatedStudentApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedProfileUserIdRoute =
  AuthenticatedProfileUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedOpportunitiesOpportunityIdRoute =
  AuthenticatedOpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingStudentRoute =
  AuthenticatedOnboardingStudentRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingGraduateRoute =
  AuthenticatedOnboardingGraduateRouteImport.update({
    id: '/graduate',
    path: '/graduate',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingBusinessRoute =
  AuthenticatedOnboardingBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGraduateDashboardRoute =
  AuthenticatedGraduateDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedGraduateRouteRoute,
  } as any)
const AuthenticatedGraduateApplicationsRoute =
  AuthenticatedGraduateApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedGraduateRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardRoute =
  AuthenticatedBusinessDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPlacementsRoute =
  AuthenticatedAdminPlacementsRouteImport.update({
    id: '/placements',
    path: '/placements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDisputesRoute =
  AuthenticatedAdminDisputesRouteImport.update({
    id: '/disputes',
    path: '/disputes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBusinessesRoute =
  AuthenticatedAdminBusinessesRouteImport.update({
    id: '/businesses',
    path: '/businesses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedBusinessOpportunitiesIndexRoute =
  AuthenticatedBusinessOpportunitiesIndexRouteImport.update({
    id: '/opportunities/',
    path: '/opportunities/',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessOpportunitiesNewRoute =
  AuthenticatedBusinessOpportunitiesNewRouteImport.update({
    id: '/opportunities/new',
    path: '/opportunities/new',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute =
  AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRouteImport.update({
    id: '/opportunities/$opportunityId/applicants',
    path: '/opportunities/$opportunityId/applicants',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/business': typeof AuthenticatedBusinessRouteRouteWithChildren
  '/graduate': typeof AuthenticatedGraduateRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/placements': typeof AuthenticatedAdminPlacementsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/graduate/applications': typeof AuthenticatedGraduateApplicationsRoute
  '/graduate/dashboard': typeof AuthenticatedGraduateDashboardRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/onboarding/graduate': typeof AuthenticatedOnboardingGraduateRoute
  '/onboarding/student': typeof AuthenticatedOnboardingStudentRoute
  '/opportunities/$opportunityId': typeof AuthenticatedOpportunitiesOpportunityIdRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/opportunities/': typeof AuthenticatedOpportunitiesIndexRoute
  '/business/opportunities/new': typeof AuthenticatedBusinessOpportunitiesNewRoute
  '/business/opportunities/': typeof AuthenticatedBusinessOpportunitiesIndexRoute
  '/business/opportunities/$opportunityId/applicants': typeof AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/business': typeof AuthenticatedBusinessRouteRouteWithChildren
  '/graduate': typeof AuthenticatedGraduateRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/placements': typeof AuthenticatedAdminPlacementsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/graduate/applications': typeof AuthenticatedGraduateApplicationsRoute
  '/graduate/dashboard': typeof AuthenticatedGraduateDashboardRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/onboarding/graduate': typeof AuthenticatedOnboardingGraduateRoute
  '/onboarding/student': typeof AuthenticatedOnboardingStudentRoute
  '/opportunities/$opportunityId': typeof AuthenticatedOpportunitiesOpportunityIdRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/opportunities': typeof AuthenticatedOpportunitiesIndexRoute
  '/business/opportunities/new': typeof AuthenticatedBusinessOpportunitiesNewRoute
  '/business/opportunities': typeof AuthenticatedBusinessOpportunitiesIndexRoute
  '/business/opportunities/$opportunityId/applicants': typeof AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/business': typeof AuthenticatedBusinessRouteRouteWithChildren
  '/_authenticated/graduate': typeof AuthenticatedGraduateRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/placements': typeof AuthenticatedAdminPlacementsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/_authenticated/graduate/applications': typeof AuthenticatedGraduateApplicationsRoute
  '/_authenticated/graduate/dashboard': typeof AuthenticatedGraduateDashboardRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/_authenticated/onboarding/graduate': typeof AuthenticatedOnboardingGraduateRoute
  '/_authenticated/onboarding/student': typeof AuthenticatedOnboardingStudentRoute
  '/_authenticated/opportunities/$opportunityId': typeof AuthenticatedOpportunitiesOpportunityIdRoute
  '/_authenticated/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/_authenticated/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/opportunities/': typeof AuthenticatedOpportunitiesIndexRoute
  '/_authenticated/business/opportunities/new': typeof AuthenticatedBusinessOpportunitiesNewRoute
  '/_authenticated/business/opportunities/': typeof AuthenticatedBusinessOpportunitiesIndexRoute
  '/_authenticated/business/opportunities/$opportunityId/applicants': typeof AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/business'
    | '/graduate'
    | '/onboarding'
    | '/student'
    | '/notifications'
    | '/profile'
    | '/reviews'
    | '/settings'
    | '/wallet'
    | '/admin/businesses'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/payouts'
    | '/admin/placements'
    | '/admin/users'
    | '/business/dashboard'
    | '/graduate/applications'
    | '/graduate/dashboard'
    | '/messages/$conversationId'
    | '/onboarding/business'
    | '/onboarding/graduate'
    | '/onboarding/student'
    | '/opportunities/$opportunityId'
    | '/profile/$userId'
    | '/student/applications'
    | '/student/dashboard'
    | '/messages/'
    | '/opportunities/'
    | '/business/opportunities/new'
    | '/business/opportunities/'
    | '/business/opportunities/$opportunityId/applicants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/business'
    | '/graduate'
    | '/onboarding'
    | '/student'
    | '/notifications'
    | '/profile'
    | '/reviews'
    | '/settings'
    | '/wallet'
    | '/admin/businesses'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/payouts'
    | '/admin/placements'
    | '/admin/users'
    | '/business/dashboard'
    | '/graduate/applications'
    | '/graduate/dashboard'
    | '/messages/$conversationId'
    | '/onboarding/business'
    | '/onboarding/graduate'
    | '/onboarding/student'
    | '/opportunities/$opportunityId'
    | '/profile/$userId'
    | '/student/applications'
    | '/student/dashboard'
    | '/messages'
    | '/opportunities'
    | '/business/opportunities/new'
    | '/business/opportunities'
    | '/business/opportunities/$opportunityId/applicants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/business'
    | '/_authenticated/graduate'
    | '/_authenticated/onboarding'
    | '/_authenticated/student'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/reviews'
    | '/_authenticated/settings'
    | '/_authenticated/wallet'
    | '/_authenticated/admin/businesses'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/disputes'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/placements'
    | '/_authenticated/admin/users'
    | '/_authenticated/business/dashboard'
    | '/_authenticated/graduate/applications'
    | '/_authenticated/graduate/dashboard'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/onboarding/business'
    | '/_authenticated/onboarding/graduate'
    | '/_authenticated/onboarding/student'
    | '/_authenticated/opportunities/$opportunityId'
    | '/_authenticated/profile/$userId'
    | '/_authenticated/student/applications'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/messages/'
    | '/_authenticated/opportunities/'
    | '/_authenticated/business/opportunities/new'
    | '/_authenticated/business/opportunities/'
    | '/_authenticated/business/opportunities/$opportunityId/applicants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/graduate': {
      id: '/_authenticated/graduate'
      path: '/graduate'
      fullPath: '/graduate'
      preLoaderRoute: typeof AuthenticatedGraduateRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities/': {
      id: '/_authenticated/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof AuthenticatedOpportunitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/applications': {
      id: '/_authenticated/student/applications'
      path: '/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof AuthenticatedStudentApplicationsRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/profile/$userId': {
      id: '/_authenticated/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/opportunities/$opportunityId': {
      id: '/_authenticated/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/opportunities/$opportunityId'
      preLoaderRoute: typeof AuthenticatedOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/student': {
      id: '/_authenticated/onboarding/student'
      path: '/student'
      fullPath: '/onboarding/student'
      preLoaderRoute: typeof AuthenticatedOnboardingStudentRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/graduate': {
      id: '/_authenticated/onboarding/graduate'
      path: '/graduate'
      fullPath: '/onboarding/graduate'
      preLoaderRoute: typeof AuthenticatedOnboardingGraduateRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/business': {
      id: '/_authenticated/onboarding/business'
      path: '/business'
      fullPath: '/onboarding/business'
      preLoaderRoute: typeof AuthenticatedOnboardingBusinessRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/graduate/dashboard': {
      id: '/_authenticated/graduate/dashboard'
      path: '/dashboard'
      fullPath: '/graduate/dashboard'
      preLoaderRoute: typeof AuthenticatedGraduateDashboardRouteImport
      parentRoute: typeof AuthenticatedGraduateRouteRoute
    }
    '/_authenticated/graduate/applications': {
      id: '/_authenticated/graduate/applications'
      path: '/applications'
      fullPath: '/graduate/applications'
      preLoaderRoute: typeof AuthenticatedGraduateApplicationsRouteImport
      parentRoute: typeof AuthenticatedGraduateRouteRoute
    }
    '/_authenticated/business/dashboard': {
      id: '/_authenticated/business/dashboard'
      path: '/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/placements': {
      id: '/_authenticated/admin/placements'
      path: '/placements'
      fullPath: '/admin/placements'
      preLoaderRoute: typeof AuthenticatedAdminPlacementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/disputes': {
      id: '/_authenticated/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AuthenticatedAdminDisputesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/businesses': {
      id: '/_authenticated/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AuthenticatedAdminBusinessesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/business/opportunities/': {
      id: '/_authenticated/business/opportunities/'
      path: '/opportunities'
      fullPath: '/business/opportunities/'
      preLoaderRoute: typeof AuthenticatedBusinessOpportunitiesIndexRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/opportunities/new': {
      id: '/_authenticated/business/opportunities/new'
      path: '/opportunities/new'
      fullPath: '/business/opportunities/new'
      preLoaderRoute: typeof AuthenticatedBusinessOpportunitiesNewRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/opportunities/$opportunityId/applicants': {
      id: '/_authenticated/business/opportunities/$opportunityId/applicants'
      path: '/opportunities/$opportunityId/applicants'
      fullPath: '/business/opportunities/$opportunityId/applicants'
      preLoaderRoute: typeof AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBusinessesRoute: typeof AuthenticatedAdminBusinessesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDisputesRoute: typeof AuthenticatedAdminDisputesRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminPlacementsRoute: typeof AuthenticatedAdminPlacementsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBusinessesRoute: AuthenticatedAdminBusinessesRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminDisputesRoute: AuthenticatedAdminDisputesRoute,
    AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
    AuthenticatedAdminPlacementsRoute: AuthenticatedAdminPlacementsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedBusinessRouteRouteChildren {
  AuthenticatedBusinessDashboardRoute: typeof AuthenticatedBusinessDashboardRoute
  AuthenticatedBusinessOpportunitiesNewRoute: typeof AuthenticatedBusinessOpportunitiesNewRoute
  AuthenticatedBusinessOpportunitiesIndexRoute: typeof AuthenticatedBusinessOpportunitiesIndexRoute
  AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute: typeof AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute
}

const AuthenticatedBusinessRouteRouteChildren: AuthenticatedBusinessRouteRouteChildren =
  {
    AuthenticatedBusinessDashboardRoute: AuthenticatedBusinessDashboardRoute,
    AuthenticatedBusinessOpportunitiesNewRoute:
      AuthenticatedBusinessOpportunitiesNewRoute,
    AuthenticatedBusinessOpportunitiesIndexRoute:
      AuthenticatedBusinessOpportunitiesIndexRoute,
    AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute:
      AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute,
  }

const AuthenticatedBusinessRouteRouteWithChildren =
  AuthenticatedBusinessRouteRoute._addFileChildren(
    AuthenticatedBusinessRouteRouteChildren,
  )

interface AuthenticatedGraduateRouteRouteChildren {
  AuthenticatedGraduateApplicationsRoute: typeof AuthenticatedGraduateApplicationsRoute
  AuthenticatedGraduateDashboardRoute: typeof AuthenticatedGraduateDashboardRoute
}

const AuthenticatedGraduateRouteRouteChildren: AuthenticatedGraduateRouteRouteChildren =
  {
    AuthenticatedGraduateApplicationsRoute:
      AuthenticatedGraduateApplicationsRoute,
    AuthenticatedGraduateDashboardRoute: AuthenticatedGraduateDashboardRoute,
  }

const AuthenticatedGraduateRouteRouteWithChildren =
  AuthenticatedGraduateRouteRoute._addFileChildren(
    AuthenticatedGraduateRouteRouteChildren,
  )

interface AuthenticatedOnboardingRouteRouteChildren {
  AuthenticatedOnboardingBusinessRoute: typeof AuthenticatedOnboardingBusinessRoute
  AuthenticatedOnboardingGraduateRoute: typeof AuthenticatedOnboardingGraduateRoute
  AuthenticatedOnboardingStudentRoute: typeof AuthenticatedOnboardingStudentRoute
}

const AuthenticatedOnboardingRouteRouteChildren: AuthenticatedOnboardingRouteRouteChildren =
  {
    AuthenticatedOnboardingBusinessRoute: AuthenticatedOnboardingBusinessRoute,
    AuthenticatedOnboardingGraduateRoute: AuthenticatedOnboardingGraduateRoute,
    AuthenticatedOnboardingStudentRoute: AuthenticatedOnboardingStudentRoute,
  }

const AuthenticatedOnboardingRouteRouteWithChildren =
  AuthenticatedOnboardingRouteRoute._addFileChildren(
    AuthenticatedOnboardingRouteRouteChildren,
  )

interface AuthenticatedStudentRouteRouteChildren {
  AuthenticatedStudentApplicationsRoute: typeof AuthenticatedStudentApplicationsRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
}

const AuthenticatedStudentRouteRouteChildren: AuthenticatedStudentRouteRouteChildren =
  {
    AuthenticatedStudentApplicationsRoute:
      AuthenticatedStudentApplicationsRoute,
    AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  }

const AuthenticatedStudentRouteRouteWithChildren =
  AuthenticatedStudentRouteRoute._addFileChildren(
    AuthenticatedStudentRouteRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileUserIdRoute: typeof AuthenticatedProfileUserIdRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileUserIdRoute: AuthenticatedProfileUserIdRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBusinessRouteRoute: typeof AuthenticatedBusinessRouteRouteWithChildren
  AuthenticatedGraduateRouteRoute: typeof AuthenticatedGraduateRouteRouteWithChildren
  AuthenticatedOnboardingRouteRoute: typeof AuthenticatedOnboardingRouteRouteWithChildren
  AuthenticatedStudentRouteRoute: typeof AuthenticatedStudentRouteRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedOpportunitiesOpportunityIdRoute: typeof AuthenticatedOpportunitiesOpportunityIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedOpportunitiesIndexRoute: typeof AuthenticatedOpportunitiesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBusinessRouteRoute: AuthenticatedBusinessRouteRouteWithChildren,
  AuthenticatedGraduateRouteRoute: AuthenticatedGraduateRouteRouteWithChildren,
  AuthenticatedOnboardingRouteRoute:
    AuthenticatedOnboardingRouteRouteWithChildren,
  AuthenticatedStudentRouteRoute: AuthenticatedStudentRouteRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedOpportunitiesOpportunityIdRoute:
    AuthenticatedOpportunitiesOpportunityIdRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedOpportunitiesIndexRoute: AuthenticatedOpportunitiesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
