/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOpportunitiesIndexRouteImport } from './routes/_authenticated/opportunities.index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student/dashboard'
import { Route as AuthenticatedStudentApplicationsRouteImport } from './routes/_authenticated/student/applications'
import { Route as AuthenticatedProfileUserIdRouteImport } from './routes/_authenticated/profile.$userId'
import { Route as AuthenticatedOpportunitiesOpportunityIdRouteImport } from './routes/_authenticated/opportunities.$opportunityId'
import { Route as AuthenticatedOnboardingStudentRouteImport } from './routes/_authenticated/onboarding/student'
import { Route as AuthenticatedOnboardingGraduateRouteImport } from './routes/_authenticated/onboarding/graduate'
import { Route as AuthenticatedOnboardingBusinessRouteImport } from './routes/_authenticated/onboarding/business'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedGraduateDashboardRouteImport } from './routes/_authenticated/graduate/dashboard'
import { Route as AuthenticatedGraduateApplicationsRouteImport } from './routes/_authenticated/graduate/applications'
import { Route as AuthenticatedBusinessDashboardRouteImport } from './routes/_authenticated/business/dashboard'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminPlacementsRouteImport } from './routes/_authenticated/admin/placements'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin/payouts'
import { Route as AuthenticatedAdminDisputesRouteImport } from './routes/_authenticated/admin/disputes'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminBusinessesRouteImport } from './routes/_authenticated/admin/businesses'
import { Route as AuthenticatedBusinessOpportunitiesIndexRouteImport } from './routes/_authenticated/business/opportunities.index'
import { Route as AuthenticatedBusinessOpportunitiesNewRouteImport } from './routes/_authenticated/business/opportunities.new'
import { Route as AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRouteImport } from './routes/_authenticated/business/opportunities.$opportunityId.applicants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/_authenticated/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/_authenticated/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/_authenticated/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/_authenticated/notifications',
    path: '/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOpportunitiesIndexRoute =
  AuthenticatedOpportunitiesIndexRouteImport.update({
    id: '/_authenticated/opportunities/',
    path: '/opportunities/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/_authenticated/messages/',
    path: '/messages/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/_authenticated/student/dashboard',
    path: '/student/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStudentApplicationsRoute =
  AuthenticatedStudentApplicationsRouteImport.update({
    id: '/_authenticated/student/applications',
    path: '/student/applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProfileUserIdRoute =
  AuthenticatedProfileUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedOpportunitiesOpportunityIdRoute =
  AuthenticatedOpportunitiesOpportunityIdRouteImport.update({
    id: '/_authenticated/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOnboardingStudentRoute =
  AuthenticatedOnboardingStudentRouteImport.update({
    id: '/_authenticated/onboarding/student',
    path: '/onboarding/student',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOnboardingGraduateRoute =
  AuthenticatedOnboardingGraduateRouteImport.update({
    id: '/_authenticated/onboarding/graduate',
    path: '/onboarding/graduate',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOnboardingBusinessRoute =
  AuthenticatedOnboardingBusinessRouteImport.update({
    id: '/_authenticated/onboarding/business',
    path: '/onboarding/business',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/_authenticated/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGraduateDashboardRoute =
  AuthenticatedGraduateDashboardRouteImport.update({
    id: '/_authenticated/graduate/dashboard',
    path: '/graduate/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGraduateApplicationsRoute =
  AuthenticatedGraduateApplicationsRouteImport.update({
    id: '/_authenticated/graduate/applications',
    path: '/graduate/applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBusinessDashboardRoute =
  AuthenticatedBusinessDashboardRouteImport.update({
    id: '/_authenticated/business/dashboard',
    path: '/business/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/_authenticated/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPlacementsRoute =
  AuthenticatedAdminPlacementsRouteImport.update({
    id: '/_authenticated/admin/placements',
    path: '/admin/placements',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/_authenticated/admin/payouts',
    path: '/admin/payouts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminDisputesRoute =
  AuthenticatedAdminDisputesRouteImport.update({
    id: '/_authenticated/admin/disputes',
    path: '/admin/disputes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/_authenticated/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminBusinessesRoute =
  AuthenticatedAdminBusinessesRouteImport.update({
    id: '/_authenticated/admin/businesses',
    path: '/admin/businesses',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBusinessOpportunitiesIndexRoute =
  AuthenticatedBusinessOpportunitiesIndexRouteImport.update({
    id: '/_authenticated/business/opportunities/',
    path: '/business/opportunities/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBusinessOpportunitiesNewRoute =
  AuthenticatedBusinessOpportunitiesNewRouteImport.update({
    id: '/_authenticated/business/opportunities/new',
    path: '/business/opportunities/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute =
  AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRouteImport.update({
    id: '/_authenticated/business/opportunities/$opportunityId/applicants',
    path: '/business/opportunities/$opportunityId/applicants',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/placements': typeof AuthenticatedAdminPlacementsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/graduate/applications': typeof AuthenticatedGraduateApplicationsRoute
  '/graduate/dashboard': typeof AuthenticatedGraduateDashboardRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/onboarding/graduate': typeof AuthenticatedOnboardingGraduateRoute
  '/onboarding/student': typeof AuthenticatedOnboardingStudentRoute
  '/opportunities/$opportunityId': typeof AuthenticatedOpportunitiesOpportunityIdRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/opportunities/': typeof AuthenticatedOpportunitiesIndexRoute
  '/business/opportunities/new': typeof AuthenticatedBusinessOpportunitiesNewRoute
  '/business/opportunities/': typeof AuthenticatedBusinessOpportunitiesIndexRoute
  '/business/opportunities/$opportunityId/applicants': typeof AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/placements': typeof AuthenticatedAdminPlacementsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/graduate/applications': typeof AuthenticatedGraduateApplicationsRoute
  '/graduate/dashboard': typeof AuthenticatedGraduateDashboardRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/onboarding/graduate': typeof AuthenticatedOnboardingGraduateRoute
  '/onboarding/student': typeof AuthenticatedOnboardingStudentRoute
  '/opportunities/$opportunityId': typeof AuthenticatedOpportunitiesOpportunityIdRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/opportunities': typeof AuthenticatedOpportunitiesIndexRoute
  '/business/opportunities/new': typeof AuthenticatedBusinessOpportunitiesNewRoute
  '/business/opportunities': typeof AuthenticatedBusinessOpportunitiesIndexRoute
  '/business/opportunities/$opportunityId/applicants': typeof AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/admin/businesses': typeof AuthenticatedAdminBusinessesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/placements': typeof AuthenticatedAdminPlacementsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/_authenticated/graduate/applications': typeof AuthenticatedGraduateApplicationsRoute
  '/_authenticated/graduate/dashboard': typeof AuthenticatedGraduateDashboardRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/_authenticated/onboarding/graduate': typeof AuthenticatedOnboardingGraduateRoute
  '/_authenticated/onboarding/student': typeof AuthenticatedOnboardingStudentRoute
  '/_authenticated/opportunities/$opportunityId': typeof AuthenticatedOpportunitiesOpportunityIdRoute
  '/_authenticated/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/_authenticated/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/opportunities/': typeof AuthenticatedOpportunitiesIndexRoute
  '/_authenticated/business/opportunities/new': typeof AuthenticatedBusinessOpportunitiesNewRoute
  '/_authenticated/business/opportunities/': typeof AuthenticatedBusinessOpportunitiesIndexRoute
  '/_authenticated/business/opportunities/$opportunityId/applicants': typeof AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/profile'
    | '/reviews'
    | '/settings'
    | '/wallet'
    | '/admin/businesses'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/payouts'
    | '/admin/placements'
    | '/admin/users'
    | '/business/dashboard'
    | '/graduate/applications'
    | '/graduate/dashboard'
    | '/messages/$conversationId'
    | '/onboarding/business'
    | '/onboarding/graduate'
    | '/onboarding/student'
    | '/opportunities/$opportunityId'
    | '/profile/$userId'
    | '/student/applications'
    | '/student/dashboard'
    | '/messages/'
    | '/opportunities/'
    | '/business/opportunities/new'
    | '/business/opportunities/'
    | '/business/opportunities/$opportunityId/applicants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/profile'
    | '/reviews'
    | '/settings'
    | '/wallet'
    | '/admin/businesses'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/payouts'
    | '/admin/placements'
    | '/admin/users'
    | '/business/dashboard'
    | '/graduate/applications'
    | '/graduate/dashboard'
    | '/messages/$conversationId'
    | '/onboarding/business'
    | '/onboarding/graduate'
    | '/onboarding/student'
    | '/opportunities/$opportunityId'
    | '/profile/$userId'
    | '/student/applications'
    | '/student/dashboard'
    | '/messages'
    | '/opportunities'
    | '/business/opportunities/new'
    | '/business/opportunities'
    | '/business/opportunities/$opportunityId/applicants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/reviews'
    | '/_authenticated/settings'
    | '/_authenticated/wallet'
    | '/_authenticated/admin/businesses'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/disputes'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/placements'
    | '/_authenticated/admin/users'
    | '/_authenticated/business/dashboard'
    | '/_authenticated/graduate/applications'
    | '/_authenticated/graduate/dashboard'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/onboarding/business'
    | '/_authenticated/onboarding/graduate'
    | '/_authenticated/onboarding/student'
    | '/_authenticated/opportunities/$opportunityId'
    | '/_authenticated/profile/$userId'
    | '/_authenticated/student/applications'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/messages/'
    | '/_authenticated/opportunities/'
    | '/_authenticated/business/opportunities/new'
    | '/_authenticated/business/opportunities/'
    | '/_authenticated/business/opportunities/$opportunityId/applicants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedAdminBusinessesRoute: typeof AuthenticatedAdminBusinessesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDisputesRoute: typeof AuthenticatedAdminDisputesRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminPlacementsRoute: typeof AuthenticatedAdminPlacementsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedBusinessDashboardRoute: typeof AuthenticatedBusinessDashboardRoute
  AuthenticatedGraduateApplicationsRoute: typeof AuthenticatedGraduateApplicationsRoute
  AuthenticatedGraduateDashboardRoute: typeof AuthenticatedGraduateDashboardRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedOnboardingBusinessRoute: typeof AuthenticatedOnboardingBusinessRoute
  AuthenticatedOnboardingGraduateRoute: typeof AuthenticatedOnboardingGraduateRoute
  AuthenticatedOnboardingStudentRoute: typeof AuthenticatedOnboardingStudentRoute
  AuthenticatedOpportunitiesOpportunityIdRoute: typeof AuthenticatedOpportunitiesOpportunityIdRoute
  AuthenticatedStudentApplicationsRoute: typeof AuthenticatedStudentApplicationsRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedOpportunitiesIndexRoute: typeof AuthenticatedOpportunitiesIndexRoute
  AuthenticatedBusinessOpportunitiesNewRoute: typeof AuthenticatedBusinessOpportunitiesNewRoute
  AuthenticatedBusinessOpportunitiesIndexRoute: typeof AuthenticatedBusinessOpportunitiesIndexRoute
  AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute: typeof AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/opportunities/': {
      id: '/_authenticated/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof AuthenticatedOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student/applications': {
      id: '/_authenticated/student/applications'
      path: '/student/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof AuthenticatedStudentApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/$userId': {
      id: '/_authenticated/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/opportunities/$opportunityId': {
      id: '/_authenticated/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/opportunities/$opportunityId'
      preLoaderRoute: typeof AuthenticatedOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding/student': {
      id: '/_authenticated/onboarding/student'
      path: '/onboarding/student'
      fullPath: '/onboarding/student'
      preLoaderRoute: typeof AuthenticatedOnboardingStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding/graduate': {
      id: '/_authenticated/onboarding/graduate'
      path: '/onboarding/graduate'
      fullPath: '/onboarding/graduate'
      preLoaderRoute: typeof AuthenticatedOnboardingGraduateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding/business': {
      id: '/_authenticated/onboarding/business'
      path: '/onboarding/business'
      fullPath: '/onboarding/business'
      preLoaderRoute: typeof AuthenticatedOnboardingBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/graduate/dashboard': {
      id: '/_authenticated/graduate/dashboard'
      path: '/graduate/dashboard'
      fullPath: '/graduate/dashboard'
      preLoaderRoute: typeof AuthenticatedGraduateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/graduate/applications': {
      id: '/_authenticated/graduate/applications'
      path: '/graduate/applications'
      fullPath: '/graduate/applications'
      preLoaderRoute: typeof AuthenticatedGraduateApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/business/dashboard': {
      id: '/_authenticated/business/dashboard'
      path: '/business/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/placements': {
      id: '/_authenticated/admin/placements'
      path: '/admin/placements'
      fullPath: '/admin/placements'
      preLoaderRoute: typeof AuthenticatedAdminPlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/disputes': {
      id: '/_authenticated/admin/disputes'
      path: '/admin/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AuthenticatedAdminDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/businesses': {
      id: '/_authenticated/admin/businesses'
      path: '/admin/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AuthenticatedAdminBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/business/opportunities/': {
      id: '/_authenticated/business/opportunities/'
      path: '/business/opportunities'
      fullPath: '/business/opportunities/'
      preLoaderRoute: typeof AuthenticatedBusinessOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/business/opportunities/new': {
      id: '/_authenticated/business/opportunities/new'
      path: '/business/opportunities/new'
      fullPath: '/business/opportunities/new'
      preLoaderRoute: typeof AuthenticatedBusinessOpportunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/business/opportunities/$opportunityId/applicants': {
      id: '/_authenticated/business/opportunities/$opportunityId/applicants'
      path: '/business/opportunities/$opportunityId/applicants'
      fullPath: '/business/opportunities/$opportunityId/applicants'
      preLoaderRoute: typeof AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileUserIdRoute: typeof AuthenticatedProfileUserIdRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileUserIdRoute: AuthenticatedProfileUserIdRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedAdminBusinessesRoute: AuthenticatedAdminBusinessesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDisputesRoute: AuthenticatedAdminDisputesRoute,
  AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
  AuthenticatedAdminPlacementsRoute: AuthenticatedAdminPlacementsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedBusinessDashboardRoute: AuthenticatedBusinessDashboardRoute,
  AuthenticatedGraduateApplicationsRoute:
    AuthenticatedGraduateApplicationsRoute,
  AuthenticatedGraduateDashboardRoute: AuthenticatedGraduateDashboardRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedOnboardingBusinessRoute: AuthenticatedOnboardingBusinessRoute,
  AuthenticatedOnboardingGraduateRoute: AuthenticatedOnboardingGraduateRoute,
  AuthenticatedOnboardingStudentRoute: AuthenticatedOnboardingStudentRoute,
  AuthenticatedOpportunitiesOpportunityIdRoute:
    AuthenticatedOpportunitiesOpportunityIdRoute,
  AuthenticatedStudentApplicationsRoute: AuthenticatedStudentApplicationsRoute,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedOpportunitiesIndexRoute: AuthenticatedOpportunitiesIndexRoute,
  AuthenticatedBusinessOpportunitiesNewRoute:
    AuthenticatedBusinessOpportunitiesNewRoute,
  AuthenticatedBusinessOpportunitiesIndexRoute:
    AuthenticatedBusinessOpportunitiesIndexRoute,
  AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute:
    AuthenticatedBusinessOpportunitiesOpportunityIdApplicantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
